ТЗ 13
EvgenyGitH/java-shareit pull request #1
Opened 2023-09-24 00:25 UTC by EvgenyGitH

2023-09-24 19:24 UTC, z8q requested changes

2023-09-24 19:24 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
Тут скорее всего опечатка, для NotBlank это для строк

2023-09-24 19:24 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +public class Comment {
Пока рановато, будет в 14-й домашке

2023-09-24 19:24 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    String status;  // WAITING - APPROVED - REJECTED - CANCELED
Тут будет Enum, в котором будут все статусы WAITING - APPROVED - REJECTED - CANCELED

2023-09-24 19:24 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    //  @NotNull
В аннотации email написано, что null elements are considered valid.
То есть если не хотим null и корректную почту, надо использовать NotNull и Email.
Email пустую строку не пропустит, значит NotBlank не нужен

2023-09-24 19:24 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImp.java
> +    //  private final ItemMapper itemMapper;
Если маппер не будем здесь использовать, можно убрать

2023-09-24 19:24 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +        if (text == null || text.isBlank()) {
В контроллере `@RequestParam` содержит в себе настройку required, которая по умолчанию true.
То есть null тут не придет, может быть только isBlank

2023-09-24 21:23 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
исправил @NotNull. 
мы здесь же можем использовать @NotEmpty?
то что я нашел в интернете @NotBlank для строк, а для остального @NotEmpty либо @NotNull в зависимости от проверки. я правильно понимаю ?

2023-09-24 21:31 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +public class Comment {
ок, в ТЗ, в начале, как-то размыто все написано ) что  должна быть возможность оставить отзыв к вещам ... )

2023-09-24 21:45 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    String status;  // WAITING - APPROVED - REJECTED - CANCELED
Добавил ENUM

2023-09-24 21:49 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    //  @NotNull
понял, спасибо ! исправил

2023-09-24 21:50 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImp.java
> +    //  private final ItemMapper itemMapper;
удалил

2023-09-24 22:04 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +        if (text == null || text.isBlank()) {
ок, спасибо за коммент! не подумал даже об этом (required). исправил

2023-09-25 18:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
NotEmpty для строк и коллекций.
NotBlank проверит на null и на пробелы `"    "` – такую строку не пропустит
NotNull проверит на null

2023-09-25 18:38 UTC, z8q approved these changes

2023-10-07 10:25 UTC, merged