according to TS14
EvgenyGitH/java-shareit pull request #2
Opened 2023-10-16 18:36 UTC by EvgenyGitH

2023-10-17 19:21 UTC, z8q requested changes

2023-10-17 19:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Component
Component здесь будет не нужен

2023-10-17 19:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@RequestBody @Valid UserDto userDto) {
Есть возможность добавить двух пользователей с одинаковыми именами и почтами

2023-10-17 19:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      }
При попытке PATCH http://localhost:8080/users/1
с таким body:
```JSON
{
	"name": "",
	"email": ""
}
```
Приходит ошибка 500, но без описания причины.
В логах описание есть 
```
ConstraintViolationImpl{interpolatedMessage='must not be blank' ...
```
Можно отлавливать через ErrorHandler и передавать текст ошибки

2023-10-17 19:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@RequestBody @Valid UserDto userDto) {
Когда создаем User с пустым полем name или некорректным email. Приходит ошибка 400, но без описаниял ошбки.
Для Item тоже применимо

2023-10-17 19:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImp.java
> +    public BookingDto createBooking(BookingDto bookingDto, Long userId) {
Методы, в которых происходят и чтение из базы, и запись, стоит оборачивать в транзакции.
Поставить над методом - `@Transactional`

2023-10-17 19:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStartBeforeAndEndAfterOrderByStartAsc(Long userId, LocalDateTime now1, LocalDateTime now2);
Когда длинна метода становиться слишком большой, стоит переписать с использованием аннотации Query, и в ней описать запрос.
Потому что в коде будет неудобно использовать методы с длинными названииями

2023-10-17 19:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImp.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new UserNotFoundException("User ID: " + userId + " not found"));
Код дублируется со строками 117-125
Возможно стоит выделить общую логику в отдельный метод

2023-10-17 21:32 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Component
исправил

2023-10-17 22:04 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImp.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new UserNotFoundException("User ID: " + userId + " not found"));
проверку State вынес в метод

2023-10-17 22:51 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImp.java
> +    public BookingDto createBooking(BookingDto bookingDto, Long userId) {
done по всем метода где чтение и запись

2023-10-17 23:37 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@RequestBody @Valid UserDto userDto) {
1. Проверку на дубль email при создании User в методе делал, но пришлось удалить. 
В пачке обсуждали этот вопрос. (... при попытке сохранить пользователя 2 его айди заинкрементится, но при попытке обновления произойдет ошибка constraint в бд. А следующее значение айди будет уже 3.) - в postman тестах проходит только без валидации в методе. 
Должно сработать поле в БД - CONSTRAINT UQ_USER_EMAIL UNIQUE (email). 

У меня вопрос: в БД PostgreSQL  поле  UNIQUE (email) срабатывает, вызывает исключение и код 500. 
а в БД H2 все проходит без проверки UNIQUE (email) и user с дублирующим email записывается без ошибки.
Не совсем понимаю почему ? (или этот вопрос задать куратору ? ) 

2. Добавил отлов исключений/описание ошибок

2023-10-17 23:38 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      }
хорошо, спасибо. Добавил отлов исключений/описание ошибок

2023-10-18 22:04 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      }
Добавил отлов исключений/ошибок. 
MethodArgumentNotValidException - нашел методы, чтобы достать Название поля и Сообщение.
ConstraintViolationException - не нашел информацию ка лучше обрабатывать (ConstraintViolationImpl{interpolatedMessage='must not be blank' ...) и как доставать Поле и сообщение. 
Описал ошибку просто текстом

2023-10-19 14:08 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStartBeforeAndEndAfterOrderByStartAsc(Long userId, LocalDateTime now1, LocalDateTime now2);
Сделал два метода через Query.

2023-10-19 20:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      }
Набросал черновой вариант
```
@ExceptionHandler(javax.validation.ConstraintViolationException.class)
    @ResponseStatus(HttpStatus.CONFLICT)
    public ErrorResponse handleConstraintViolationException(javax.validation.ConstraintViolationException exception) {
        var messages = exception.getConstraintViolations().stream().map(ConstraintViolation::getMessage).collect(Collectors.toSet());
        for (var message : messages) {
            log.info("Validation error: {}", message);
        }
        return new ErrorResponse("Email already exists");
    }
```
Обрати внимание на импорты, путь к ConstraintViolationException. Должен быть javax.validation

2023-10-19 20:05 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@RequestBody @Valid UserDto userDto) {
Тут лучше к куратору, надо тестировать.

2023-10-19 20:06 UTC, z8q approved these changes

2023-10-19 21:47 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      }
Спасибо !!!

2023-10-19 21:49 UTC, merged