TZ15
EvgenyGitH/java-shareit pull request #3
Opened 2023-10-26 23:04 UTC by EvgenyGitH

2023-11-03 03:53 UTC, z8q requested changes

2023-11-03 03:53 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        if (from < 0 || size <= 0) {
Аннотации PositiveOrZero, Positive не работают?
Можно попробовать поставить над классом контроллера  `@Validated` и убрать этот блок if.

2023-11-03 03:53 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (from < 0 || size <= 0) {
В request-контроллере писал про блок if.  Тут тоже применимо

2023-11-03 03:53 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (from < 0 || size <= 0) {
И в booking-контроллере

2023-11-03 15:07 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        if (from < 0 || size <= 0) {
исправил, теперь работают

2023-11-03 15:08 UTC, EvgenyGitH commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (from < 0 || size <= 0) {
done

2023-11-04 01:30 UTC, z8q approved these changes

2023-11-04 14:42 UTC, merged