according to TZ16
EvgenyGitH/java-shareit pull request #4
Opened 2023-11-08 19:08 UTC by EvgenyGitH

2023-11-09 19:05 UTC, z8q requested changes

2023-11-09 19:05 UTC, z8q commented on docker-compose.yaml
> +  #    - SPRING_DATASOURCE_PASSWORD=ushareit
С этими переменными не работает?
Postgres-овые нужно в db применять, 
тут – SPRING_DATASOURCE

2023-11-09 19:05 UTC, z8q commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Стоит посмотреть, есть ли необходимость в этой зависимости.
По тз вся логика валидации должна проходить на gateway. Если зависимость не будет использоваться, ее тоже нужно будет убрать

2023-11-09 19:05 UTC, z8q commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> update(//@RequestHeader("X-ShareIt-User-Id") Long id,
Закомментированные блоки лучше убрать, если не будут использоваться

2023-11-09 19:15 UTC, EvgenyGitH commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> update(//@RequestHeader("X-ShareIt-User-Id") Long id,
done

2023-11-09 19:18 UTC, EvgenyGitH commented on docker-compose.yaml
> +  #    - SPRING_DATASOURCE_PASSWORD=ushareit
у меня были проблемы с application.properties он не считывался. я все варианты пробовал. забыл вернуть. Исправил

2023-11-09 19:33 UTC, EvgenyGitH commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
да, в целом все параметры на входе проверяются в gateway, а то что отправляется в БД, формируется в модуле server. убрал валидацию

2023-11-10 13:14 UTC, z8q approved these changes

2023-11-18 11:43 UTC, merged